version: "3"
services:
  springboot-app:
    image: springboot-app
    restart: always
    build: .
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_PORT: 3306

  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - ./dataStore:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: DSaula
      MYSQL_ROOT_PASSWORD: Banco123