INSERT INTO instituto (NOME, ACRONIMO, STATUS)
VALUES ('Universidade Federal do Rio de Janeiro', 'UFRJ', 1)
ON DUPLICATE KEY UPDATE ACRONIMO = ACRONIMO;

INSERT INTO instituto (NOME, ACRONIMO, STATUS)
VALUES ('Instituto Federal', 'IFF', 1)
ON DUPLICATE KEY UPDATE ACRONIMO = ACRONIMO;

INSERT INTO instituto (NOME, ACRONIMO, STATUS)
VALUES ('Universidade Estadual do Rio de Janeiro', 'ACR', 1)
ON DUPLICATE KEY UPDATE ACRONIMO = ACRONIMO;

INSERT INTO instituto (NOME, ACRONIMO, STATUS)
VALUES ('Universidade Federal Fluminense', 'UFF', 1)
ON DUPLICATE KEY UPDATE ACRONIMO = ACRONIMO;